### ISSUE TITLE
Inheritance does not compile when overriding properties with `default` methods

### ISSUE THREAD

**Issue by laterlev** [danielnorberg/auto-matter#203]
```
    @AutoMatter
    interface SuperType {

        @JsonProperty
        String field();

        @JsonProperty
        String overrideMe();
    }

    @AutoMatter
    interface SubType extends SuperType {

        @Override
        @JsonProperty
        default String overrideMe() {
               return "overridden hardcoded value";
        }
    }
```
which generates the following

```
  final class SubTypeBuilder {
      
      private String field;
  
      private SubTypeBuilder(SuperType v) {
           this.overrideMe= v.overrideMe();
       }
       
       ....
  }
```
where `overrideMe` is not a class variable because it was overridden by a `default` method thus causing a compile error

tried fixing this locally and had success by checking whether the method is default here: https://github.com/danielnorberg/auto-matter/blob/master/processor/src/main/java/io/norberg/automatter/processor/AutoMatterProcessor.java#L411-L415

and skipping if it was, happy to open a PR if it helps

**Comment by danielnorberg** [comment]
Sorry for missing this, will take a look. Would happily take a PR.

**Comment by laterlev** [comment]
@danielnorberg thanks for addressing this!
