### ISSUE TITLE
Excessive depency on h2 from modelshape

### ISSUE THREAD

**Issue by lepistone** [danielnorberg/auto-matter#233]
It seems that auto-matter pulls in the h2 database through modeshape-common. Modeshape is only used to get the `singularize` method out of an `Inflector`.

It would be nice to avoid pulling a full database and modeshape itself for that. As an alternative, maybe there is a lighter-weight inflector from another library or alternatively this `Inflector` could be vendored in?

Thanks!

**Comment by danielnorberg** [comment]
The h2 exclusion has been released. Created a PR to vendor the inflector and remove the modeshape dep: https://github.com/danielnorberg/auto-matter/pull/234

**Comment by lepistone** [comment]
Great! I hadn't noticed the merged PR for excluding h2.

**Comment by lepistone** [comment]
Fixed in #234.
