### ISSUE TITLE
Helper method to fill in dummy values reduce boilerplate code when testing

### ISSUE THREAD

**Issue by mrunesson** [danielnorberg/auto-matter#27]
Would it be possible to add a build method or another method on the builderobject that populates all not null values with dummy values. This would be useful when writing unit tests and reduce boilerplate code when you only care for some fields.

**Comment by danielnorberg** [comment]
How would you like this API to look?

**Comment by mrunesson** [comment]
I have been thinking something like this:

@AutoMatter
  public interface Gazonk {
    String foo();
    @Nullable String bar();
    @Nullable Integer number();
  }

new GazonkBuilder().foo("value").setNullableFields().build()
Gives a record:
{ "foo": "value", "bar":"", "number": 0}

And:
new GazonkBuilder().foo("value").number(5).setNullableFields().build()
Gives a record:
{ "foo": "value", "bar":"", "number": 5}

So the method setNullableFields() fills in all Nullable fields not yet set to any value.

**Comment by danielnorberg** [comment]
Something like this seems like it could be useful for records involving many fields. I have two thoughts about this though. 

1. A method to only set `@Nullable` fields seems awfully specific. Is there some natural property of `@Nullable` that should make those fields "default-initializable" or is this actually something that generalizes to non-`@Nullable` fields as well? I.e., have some method `.setDefaults()` that would initialize all fields to some "default" values.

2. Defaults for primitives and String etc seems somewhat straightforward. What should the default value for a field of the arbitrary type `Foo` be?

**Comment by mrunesson** [comment]
Oups! I inverted @Nullable I meant @NotNull in previous post.

1. I see it as a trade off. setDefaults is fine too. I was leaning back and forth between those two variants. Reason I went for only setting on non nullable fields was that you might have a test case where you want to set a field that can be null to null. .setDefault complicates that.

2. That is tricky. Normal what I ends up in is using the default constructor or if it is a AutoMatter object setting all fields that must have a value.

It is definitely not easy to find a perfect solution.

**Comment by danielnorberg** [comment]
Sorry for the late reply. Saw your comment just now.

It's not clear to me what a good general solution for this is. It seems like maybe you could address your use case using reflection though.

I.e.

```java
public static <B> B withNotNullDefaults(Class<?> valueClass, B builder) {
  // 1. Reflect on valueClass and iterate over all fields
  // 2. If @NotNull, invoke setter on builder with some desired default
  return builder;
}

// ...

FoobarBuilder builder = withNotNullDefaults(Foobar.builder());

// Do something with builder ...
```

Would that work?

**Comment by mrunesson** [comment]
I think that could work. Will try to get some time to do some experimentation with your idea.

**Comment by danielnorberg** [comment]
@mrunesson did you manage to solve this issue?

**Comment by mrunesson** [comment]
I ended up doing some utility methods for my usecase.
