### ISSUE TITLE
NPE on from() when nullable collection unset (since 0.22)

### ISSUE THREAD

**Issue by tlcs** [danielnorberg/auto-matter#293]
I've noticed that in all the versions since 0.22 there was a change behaviour which causes a NullPointerExcection.

**Step to reproduce:**
- use Nullable annotation on a field which is a collection
- create a builder with that collection left unset
- try to copy that builder using `from()` method

**Expected behaviour:** copy of the builder is created (with nullable collection set to null)
**Actual behaviour:**  NPE is thrown due to nullable collection being unset

Earlier version - 0.21 - worked as expected.

## Example

Builder:

```java
    @AutoMatter
    public interface Foobar {
        @Nullable
        List<String> fruits();
    }
```

Usage:

```java
        // regular builder usage with nullable works fine
        var builder = new FoobarBuilder().build();
        assert builder.fruits() == null;

        // copying builder works as expected if nullable field is set on the source builder
        var builderWithNullableSet = new FoobarBuilder().fruits("banana");
        var builderCopy = FoobarBuilder.from(builderWithNullableSet);
        assert builderCopy.fruits().equals(List.of("banana"));

        // copying builder throws NPE if nullable collection not set on the source builder
        var builderWithNullableUnset = new FoobarBuilder();
        // throws NPE:  Cannot invoke "java.util.Collection.toArray()" because "c" is null
        FoobarBuilder.from(builderWithNullableUnset);
```

## Suspected cause

I believe that this behaviour was caused by this change (Fix Spotbugs complaints):
#184 

As it removed extra null checks - e.g. the generated code in builders changed from: 
```java
this.foos = (v.foos() == null) ? null : new ArrayList<T>(v.foos());
```

to
```java
this.foos = new ArrayList<T>(v.foos());
```

It may as well be that I missed some context and I am not right about it, but it looks to me like a bug.

**Comment by danielnorberg** [comment]
This indeed seems like a bug. Would you like to contribute a fix?

**Comment by tlcs** [comment]
Thanks for the swift reply. And Sure!

And would you be fine (in principle) if I just restored those checks removed earlier?  To me that seems like the simplest way to go.

**Comment by danielnorberg** [comment]
Sounds good. Don’t remember now exactly why spotbugs complained though.

**Comment by danielnorberg** [comment]
Fixed in https://github.com/danielnorberg/auto-matter/releases/tag/v0.26.1.
