### ISSUE TITLE
@JsonCreator annotation overwritten by the Jackson AutoMatterModule

### ISSUE THREAD

**Issue by mbruggmann** [danielnorberg/auto-matter#36]
Found this the other day when I tried to parse a 2-element JSON list into a Guava range using a custom `@JsonCreator` Jackson annotation on a AutoMatter interface. The cause seems to be that the module always treats the constructor of the generated value type as the creator method.

Testcase:
```java
public class JsonCreatorExample {

  @AutoMatter
  public interface WithJsonCreator {
    int val();

    @JsonCreator static WithJsonCreator of(final int val) {
      return new WithJsonCreatorBuilder().val(val+1).build();
    }
  }

  public static void main(final String... args) throws IOException {
    final WithJsonCreator c = new ObjectMapper()
        .registerModule(new AutoMatterModule())
        .readValue("{ \"val\": 3 }", WithJsonCreator.class);
    System.out.println(c.val());
  }
}
```

**Comment by danielnorberg** [comment]
Yes, `AutoMatterResolver` tells jackson that it should use the `WithJsonCreatorBuilder$Value` class when deserializing, so very likely jackson never even looks for creator methods in `WithJsonCreator`.

Maybe you can use `@JsonSerialize` and `@JsonDeserialize` instead to customize the serialization/deserialization of the range field? 

https://fasterxml.github.io/jackson-databind/javadoc/2.3.0/com/fasterxml/jackson/databind/annotation/JsonSerialize.html

https://fasterxml.github.io/jackson-databind/javadoc/2.3.0/com/fasterxml/jackson/databind/annotation/JsonDeserialize.html

**Comment by danielnorberg** [comment]
@mbruggmann did you manage to solve your issue?

**Comment by danielnorberg** [comment]
@mbruggmann Is this still an issue or can I close it? =)

**Comment by mbruggmann** [comment]
@danielnorberg We did work around it.
