### ISSUE TITLE
Deserialising field named "private"

### ISSUE THREAD

**Issue by i11** [danielnorberg/auto-matter#37]
Hello,

I was wondering whether anyone would have any ideas on how to declare and gson deserialise an entity with a field named "private"?

Thanks!

**Comment by danielnorberg** [comment]
I guess you could use `@SerializedName` and do something like this: 

```java
@AutoMatter
interface Foobar {
  @SerializedName("private") boolean isPrivate();
}
```

https://google.github.io/gson/apidocs/com/google/gson/annotations/SerializedName.html

**Comment by lndbrg** [comment]
Isn't that annotation lost in the generated sources? (Also the gson reflective type adapter works on fields and not on methods, so even if that method is annotated with that, gson will still not pick it up as it is a method not a field, right?)
