### ISSUE TITLE
Wrong hashcode method for classes with a field name "result"

### ISSUE THREAD

**Issue by acq** [danielnorberg/auto-matter#45]
Let's say I want a model matching the following Json:

```
{
  "result": "OK"
}
```

I would create an AutoMatter class like this:

```
@AutoMatter
public interface RestResult {
    String result();
}
```

The current version of AutoMatter would generate the following `hashCode()` function:

```
@Override
public int hashCode() {
  int result = 1;
  long temp;
  result = 31 * result + (result != null ? result.hashCode() : 0);
  return result;
}
```

This would not compile because there is a conflict between the ivar `result` and the field with the same name.
The proper code should be :

```
@Override
public int hashCode() {
  int result = 1;
  long temp;
  result = 31 * result + (this.result != null ? this.result.hashCode() : 0);
  return result;
}
```

So the library would need to add `this.` when referencing fields to avoid conflicts with method's variables.

**Comment by danielnorberg** [comment]
Good catch 👍  Would you like to submit a PR to fix this issue?

**Comment by acq** [comment]
Hi.
Sorry for taking so long.
Here is the PR : https://github.com/danielnorberg/auto-matter/pull/46
