### ISSUE TITLE
Does not support inheritance of generic Collection

### ISSUE THREAD

**Issue by vincentbrison** [danielnorberg/auto-matter#47]
Hi,
Let's say I have the following classes :
```
@AutoMatter
public interface Foo<T> {
    List<T> foos();
}
```
and 
```
@AutoMatter
public interface Bar extends Foo<Integer> {
}
```

The generated `BarBuilder` is manipulating `List<? extends T>` instead of `List<? extends Integer>`, resulting in building error.

I suppose this is not intended ?
BR

**Comment by danielnorberg** [comment]
Indeed, this seems like a bug. I'll happily accept PR's to fix it =)

**Comment by petedmarsh** [comment]
I took a look at this and I think the problem has since been fixed, I've raised https://github.com/danielnorberg/auto-matter/pull/58 which adds a test for the expected behavior.

**Comment by danielnorberg** [comment]
Closing as this seems to have been fixed.
