### ISSUE TITLE
Add feature guide

### ISSUE THREAD

**Issue by vincentbrison** [danielnorberg/auto-matter#49]
Hi,

I would like to contribute minor improvements to this library. Do you have any plan for the futur for this project ? Do you have any guide for contributing to the project ?

For example I just added `@Nullable` to builder setters parameters if the value is defined as `@Nullable` in the interface : https://github.com/vincentbrison/auto-matter/commit/2bfa2b9d313f26ffa4d90b0cd1fc52e20ec778f5

I think it would be a nice feature since the developer would directly know if a field can be null or no when building it. Can I send you a PR for it ?

**Comment by danielnorberg** [comment]
Hi, sorry for the late reply!

We're using auto-matter project at Spotify and the project is being maintained although we're not currently actively adding new features. I don't really have a contribution guide, but PR's are welcome.
