### ISSUE TITLE
generic type miss match when field is Optional<List<T>>

### ISSUE THREAD

**Issue by williamdotyang** [danielnorberg/auto-matter#60]
As we talked about in the Slack channel...

When I wanted to make a generic type interface with automatter and have a field type that's nested with Optional and List, the generated code is incorrect in handling the types. 

The issue I had was the following interface definition
`@AutoMatter`
`public interface ResponseAndEvents<T> {`
`    Response response();`
`    Optional<List<T>> eventsMaybe()`
`}`

**Comment by danielnorberg** [comment]
Closing as this should be fixed now, try upgrading to auto-matter 0.15.0. Please reopen if it still does not work for you.
